version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - ./web/source:/web/source
    command:
      "python3 web/source/manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web